<template>
  <el-card class="page-card">
    <div class="page-toolbar"><el-input v-model="query.username" placeholder="账号" clearable style="width:180px"/><el-input v-model="query.nickname" placeholder="用户名" clearable style="width:180px"/><el-button type="primary" @click="load">查询</el-button><el-button @click="resetQuery">重置</el-button><span class="spacer"></span><el-button type="primary" :icon="Plus" @click="open()">新增用户</el-button></div>
    <el-table :data="rows" stripe v-loading="loading"><el-table-column prop="username" label="账号"/><el-table-column prop="nickname" label="用户名"/><el-table-column prop="phone" label="手机号"/><el-table-column prop="email" label="邮箱" min-width="160"/><el-table-column label="角色"><template #default="s"><el-tag v-for="x in s.row.roleNames" :key="x" size="small" class="role-tag">{{x}}</el-tag></template></el-table-column><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="s.row.status===1?'success':'info'">{{s.row.status===1?'启用':'禁用'}}</el-tag></template></el-table-column><el-table-column prop="createTime" label="创建时间" width="180"/><el-table-column label="操作" width="235" fixed="right"><template #default="s"><el-button link type="primary" @click="open(s.row)">编辑</el-button><el-button link type="warning" @click="password(s.row)">重置密码</el-button><el-button link type="danger" :disabled="s.row.username==='admin'" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table>
    <el-pagination class="pagination" v-model:current-page="query.pageNum" v-model:page-size="query.pageSize" :total="total" layout="total, prev, pager, next" @change="load"/>
  </el-card>
  <el-dialog v-model="dialog" :title="form.id?'编辑用户':'新增用户'" width="560px"><el-form ref="formRef" :model="form" :rules="rules" label-width="88px"><el-row :gutter="16"><el-col :span="12"><el-form-item label="账号" prop="username"><el-input v-model="form.username"/></el-form-item></el-col><el-col :span="12"><el-form-item label="用户名" prop="nickname"><el-input v-model="form.nickname"/></el-form-item></el-col><el-col v-if="!form.id" :span="12"><el-form-item label="初始密码" prop="password"><el-input v-model="form.password" type="password" show-password/></el-form-item></el-col><el-col :span="12"><el-form-item label="状态"><el-switch v-model="form.status" :active-value="1" :inactive-value="0"/></el-form-item></el-col><el-col :span="12"><el-form-item label="手机号"><el-input v-model="form.phone"/></el-form-item></el-col><el-col :span="12"><el-form-item label="邮箱" prop="email"><el-input v-model="form.email"/></el-form-item></el-col><el-col :span="24"><el-form-item label="角色"><el-select v-model="form.roleIds" multiple style="width:100%"><el-option v-for="r in roles" :key="r.id" :label="r.roleName" :value="r.id"/></el-select></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';import { Plus } from '@element-plus/icons-vue';import { ElMessage,ElMessageBox,type FormInstance } from 'element-plus';import {getUserPage,getRoleList,createUser,updateUser,deleteUser,resetPassword} from '@/api/system'
const query=reactive({pageNum:1,pageSize:10,username:'',nickname:''}),rows=ref<any[]>([]),roles=ref<any[]>([]),total=ref(0),loading=ref(false),dialog=ref(false),formRef=ref<FormInstance>();const empty=()=>({id:0,username:'',nickname:'',password:'123456',phone:'',email:'',status:1,roleIds:[] as number[]});const form=reactive(empty());const rules={username:[{required:true,message:'请输入账号'}],nickname:[{required:true,message:'请输入用户名'}],password:[{min:6,message:'至少 6 位'}],email:[{type:'email',message:'邮箱格式不正确'}]}
const load=async()=>{loading.value=true;try{const d=await getUserPage(query);rows.value=d.records;total.value=d.total}finally{loading.value=false}};const resetQuery=()=>{query.username='';query.nickname='';query.pageNum=1;load()};const open=(row?:any)=>{Object.assign(form,empty(),row||{});form.roleIds=[...(row?.roleIds||[])];dialog.value=true};const save=async()=>{if(!await formRef.value?.validate().catch(()=>false))return;form.id?await updateUser(form.id,form):await createUser(form);ElMessage.success('保存成功');dialog.value=false;load()};const remove=async(row:any)=>{await ElMessageBox.confirm(`确定删除用户“${row.nickname}”吗？`,'提示',{type:'warning'});await deleteUser(row.id);ElMessage.success('删除成功');load()};const password=async(row:any)=>{const {value}=await ElMessageBox.prompt('请输入新密码（至少 6 位）',`重置 ${row.username} 的密码`,{inputType:'password',inputPattern:/.{6,}/,inputErrorMessage:'密码至少 6 位'});await resetPassword(row.id,value);ElMessage.success('密码已重置')};onMounted(async()=>{roles.value=await getRoleList();load()})
</script>
<style scoped>.role-tag{margin-right:5px}.pagination{justify-content:flex-end;margin-top:18px}</style>
